version: '3.8'
services:
  node-server:
    container_name: node-server
    build:
      context: .
      dockerfile: ./service/Node.Dockerfile
    volumes:
      - './api-server-nodejs:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    networks:
      - web_network
  react-ui:
    container_name: react-soft-ui
    build:
      context: .
      dockerfile: ./service/React.Dockerfile
    volumes:
      - './react-ui:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    networks:
      - web_network
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
